input_data_path: "data/raw/telecom_data_test.csv"
model_path: "models/random_forest.pkl"
predict_path: "data/predicted/predict_random_forest.csv"
transformer_path: "models/transformer_random_forest.pkl"
target_col: "Churn"
clean_features:
  nulls: "TotalCharges"
  outliers: "TotalCharges"
  target: "Churn"