input_data_path: "data/raw/telecom_data_test.csv"
model_path: "models/grad_boost.pkl"
predict_path: "data/predicted/predict_grad_boost.csv"
transformer_path: "models/transformer_grad_boost.pkl"
target_col: "Churn"
clean_features:
  nulls: "TotalCharges"
  outliers: "TotalCharges"
  target: "Churn"