input_data_path: "data/raw/heart.csv"
metric_path: "models/metrics_train_grad_boost.json"
save_model_path: "models/grad_boost.pkl"
save_transformer_path: "models/transformer_grad_boost.pkl"

downloading_params:
  file_link: "https://drive.google.com/file/d/1FU8p1PG7O_nGKvpjFXuXfoWDPCBvm8xS/view?usp=sharing"
  output_folder: "data/raw/"
  name: "data.zip"

model_type:
  model_type: "GradientBoostingClassifier"
  n_estimators: 200
  min_samples_leaf: 5

clean_features:
  outliers: "RestingBP"
  nulls: "Cholesterol"
  target: "HeartDisease"

custom_transformer:
  use_custom_transformer: false

feature_params:
  cat_features:
    - "Sex"
    - "ChestPainType"
    - "FastingBS"
    - "RestingECG"
    - "ExerciseAngina"
    - "ST_Slope"
  num_features:
    - "Age"
    - "RestingBP"
    - "Cholesterol"
    - "MaxHR"
    - "Oldpeak"
  target: "HeartDisease"

splitting_params:
  test_size: 0.3
  random_state: 0


