input_data_path: "data/raw/telecom_data_train.csv"
metric_path: "models/metrics_train_random_forest.json"
save_model_path: "models/random_forest.pkl"
save_transformer_path: "models/transformer_random_forest.pkl"

downloading_params:
  file_link: "https://drive.google.com/file/d/1dpqOgGEmBQePmDcpUYighbDngfq6RoEl/view?usp=sharing"
  output_folder: "data/raw/"
  name: "data.zip"

model_type:
  model_type: "RandomForestClassifier"
  n_estimators: 200
  min_samples_leaf: 5

clean_features:
  nulls: "TotalCharges"
  outliers: "TotalCharges"
  target: "Churn"

custom_transformer:
  use_custom_transformer: false

feature_params:
  cat_features:
    - 'gender'
    - 'SeniorCitizen'
    - 'Partner'
    - 'Dependents'
    - 'PhoneService'
    - 'MultipleLines'
    - 'InternetService'
    - 'OnlineSecurity'
    - 'OnlineBackup'
    - 'DeviceProtection'
    - 'TechSupport'
    - 'StreamingTV'
    - 'StreamingMovies'
    - 'Contract'
    - 'PaperlessBilling'
    - 'PaymentMethod'

  num_features:
    - 'tenure'
    - 'MonthlyCharges'
    - "TotalCharges"

  target: "Churn"


splitting_params:
  test_size: 0.3
  random_state: 42
